#53: Membuat kategori baru berdasarkan threshold (ambang batas)

Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [2]:
d = {'hobi':['jogging', 'mancing', 'renang',
             'mancing', 'mancing', 'baca', 
             'baca', 'mancing', 'fotograsi', 
             'mancing', 'camping']}

df = pd.DataFrame(d)
df

         hobi
0     jogging
1     mancing
2      renang
3     mancing
4     mancing
5        baca
6        baca
7     mancing
8   fotograsi
9     mancing
10    camping

Membuat kategori baru berdasarkan threshold (ambang batas)

In [3]:
df['hobi'].value_counts()

hobi
mancing      5
baca         2
jogging      1
renang       1
fotograsi    1
camping      1
Name: count, dtype: int64

In [4]:
persentase = df['hobi'].value_counts(normalize=True)
persentase

hobi
mancing      0.454545
baca         0.181818
jogging      0.090909
renang       0.090909
fotograsi    0.090909
camping      0.090909
Name: proportion, dtype: float64

In [5]:
threshold = 0.1
hobi_lain = persentase[persentase < threshold].index
hobi_lain

Index(['jogging', 'renang', 'fotograsi', 'camping'], dtype='object', name='hobi')

In [6]:
df['hobi'] = df['hobi'].replace(hobi_lain, 'lainnya')
df['hobi']

0     lainnya
1     mancing
2     lainnya
3     mancing
4     mancing
5        baca
6        baca
7     mancing
8     lainnya
9     mancing
10    lainnya
Name: hobi, dtype: object

In [7]:
df['hobi'].value_counts(normalize=True)

hobi
mancing    0.454545
lainnya    0.363636
baca       0.181818
Name: proportion, dtype: float64

54: Menyimpan Data Frame sebagai file CSV

In [8]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [9]:
data = {'nama':['bayu', 'indra', 'devi','agni'], 
             'jenis_kelamin': ['L', 'L', 'P', 'L'],
             'usia': [23, 21, 22, 25]}

df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

Menyimpan Data Frame sebagai file CSV

In [10]:
df.to_csv('data_peserta.csv')

In [11]:
df = pd.read_csv('data_peserta.csv')

df

   Unnamed: 0   nama jenis_kelamin  usia
0           0   bayu             L    23
1           1  indra             L    21
2           2   devi             P    22
3           3   agni             L    25

In [12]:
df.to_csv('data_peserta.csv', index=False)
df = pd.read_csv('data_peserta.csv')
df

   Unnamed: 0   nama jenis_kelamin  usia
0           0   bayu             L    23
1           1  indra             L    21
2           2   devi             P    22
3           3   agni             L    25

#55: Menghitung jumlah baris menurut kriteria tertentu

In [13]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

Persiapan Data Frame

In [14]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)),
    columns=cols)
df

   A  B  C  D  E
0  4  9  4  6  1
1  8  8  5  2  9
2  3  2  2  5  8
3  8  1  8  1  5
4  8  2  9  4  7
5  4  8  7  3  7
6  9  4  2  2  6
7  7  4  6  9  8
8  2  6  5  6  3
9  4  1  7  2  5

Menghitung jumlah baris menurut kriteria tertentu

In [15]:
(df['A'] < 5).sum()

np.int64(5)

In [16]:
(df['A'] < 5).mean()

np.float64(0.5)

56: Mengeluarkan kolom dari Data Frame

In [17]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [18]:
data = {
    'nama': ['bayu', 'indra', 'devi', 'agni'],
    'jenis_kelamin': ['L', 'L', 'P', 'L'],
    'usia': [23, 21, 22, 25]
}
df = pd.DataFrame(data)
df

    nama jenis_kelamin  usia
0   bayu             L    23
1  indra             L    21
2   devi             P    22
3   agni             L    25

Mengeluarkan Kolom dari Data Frame

In [19]:
usia = df.pop('usia').to_frame()

In [20]:
df

    nama jenis_kelamin
0   bayu             L
1  indra             L
2   devi             P
3   agni             L

In [21]:
df

    nama jenis_kelamin
0   bayu             L
1  indra             L
2   devi             P
3   agni             L

In [22]:
usia

   usia
0    23
1    21
2    22
3    25